[package]
name = "cex_common"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
jsonwebtoken = "9.3.0"
reqwest = { version = "0.12.0", features = ["json"] }
# serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"